theme: minima
title: Hey there!! Welcome to my page
author: Dineshkumar
email: dineshkumarsrds1999@gmail.com
description: > # this means to ignore newlines until "baseurl:"
👉 Founder of InsightMonkeys and Inainthu Sei Maatram Kaann
👉 learning DevOps tools and pipelines
👉 Microsoft Learn Student 
👉 member of Azure Developer Community 

# social links
twitter_username: dinesh_1866
github_username:  Dinesh1866

show_excerpts: true # set to false to remove excerpts on the homepage
